apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: error-count
spec:
  description: Number of error responses
  params:
  - name: query
    value: |
      sum(increase(revision_app_request_latencies_count{response_code_class!='2xx',revision_name='$revision'}[$elapsedTime])) or on() vector(0)
  type: counter
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
