apiVersion: iter8.tools/v2alpha2
kind: Metric
metadata:
  name: mean-latency
spec:
  description: Mean latency
  units: milliseconds
  params:
  - name: query
    value: |
      (sum(increase(revision_app_request_latencies_sum{revision_name='$revision'}[$interval])) or on() vector(0)) / (sum(increase(revision_app_request_latencies_count{revision_name='$revision'}[$interval])) or on() vector(0))
  type: gauge
  sampleSize: request-count
  provider: prometheus
  jqExpression: ".data.result[0].value[1] | tonumber"
  urlTemplate: http://prometheus-operated.iter8-system:9090/api/v1/query
