# This cluster role binding enables Iter8 controller and handler to manipulate 
# Iter8 experiments in the cluster in any namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: experiments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: experiments
subjects:
- kind: ServiceAccount
  name: controller
- kind: ServiceAccount
  name: handlers
---
# This cluster role binding enables Iter8 controller and handlers to read 
# Iter8 metrics in the cluster in any namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics
subjects:
- kind: ServiceAccount
  name: controller
- kind: ServiceAccount
  name: handlers
---
# This role binding authorizes Iter8 controller to manipulate 
# jobs in the cluster in Iter8 namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs
subjects:
- kind: ServiceAccount
  name: controller
---
# Helm v3 uses secrets to store Helm release information.
# 
# By default, when Helm is used within Iter8 experiments, secrets 
# will be located in the Iter8 namespace.
#
# This role binding enables Iter8 handler to read 
# secrets in the namespace where Iter8 is installed
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-handler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: handlers
---
# Helm v3 uses secrets to store Helm release information.
# 
# By default, when Helm is used within Iter8 experiments, secrets 
# will be located in the Iter8 namespace.
#
# This role binding enables Iter8 handler to write 
# secrets in the namespace where Iter8 is installed
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-handler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-writer
subjects:
- kind: ServiceAccount
  name: handlers
---
# Iter8 analytics may use secrets to populate authentication information
# in REST query headers while querying metrics backends.
# 
# This role binding authorizes Iter8 analytics to read 
# secrets in the namespace where Iter8 is installed.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: analytics
---
# This role binding enables Iter8 controller to perform 
# leader election in the namespace where Iter8 is installed
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller
---
